trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: 'snakes.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'snakes.sln'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishProfile: '$(WebDeployPublishProfile)'
    projects: 'snakes.csproj'
    configuration: 'Release'
    zipAfterPublish: true